# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  database: musicapp_development
  pool: 5

test:
  <<: *default
  database: musicapp_test

production:
  <<: *default
  database: musicapp_production
  username: ENV['RDS_USERNAME']
  password: ENV['RDS_PASSWORD']
  host: ENV['RDS_HOST']
